### ISSUE TITLE
caniusepython3 doesn't check python3 compatibility with packages versions

### ISSUE THREAD

**Issue by ciarancourtney** [brettcannon/caniusepython3#162]
e.g. if you have a package "Django==1.4.22" in your requirements.txt, it will get flagged as python3 compatible because later versions of django support python3.

It would be better if caniusepython3 checked the specific package version, and then returned the minimum version required to upgrade to python3.

Excuse me if this is already a feature, but it doesn't seem obvious from the documentation

**Comment by brettcannon** [comment]
This is by design as the expectation is if you're adding support for Python 3 you will most likely need to upgrade your dependencies as well in order to pick up their Python 3 support. The whole system is also not designed to support version info, e.g. the overrides file only worries about the latest release on PyPI and doesn't have any version details.

Thanks for the idea but I don't think it's worth the complexity overhead in order to add support for it.

**Comment by rednaks** [comment]
I have a PR for this use case :) #210
